
figure:
  size: 
    width: 8
    height: 3

  row: 3
  col: 1

tracks:
  - name: M2
    type: bw
    gs:
      row:
        from: 0
        to: 
      col: 
        from: 0
        to:

    pars:
      bwfile: /annoroad/data1/bioinfo/PMO/yuanzan/RD/WDL/bw_track5/script/M2A.bw
      chrom: chr13
      start: 72000000
      end: 76000000
      color: '#464451'
      resolution: 5000

  - name: D1
    type: bw
    gs:
      row:
        from: 1
        to: 
      col: 
        from: 0
        to: 

    pars:
      bwfile: /annoroad/data1/bioinfo/PMO/yuanzan/RD/WDL/bw_track5/script/D1A.bw
      chrom: chr13
      start: 72000000
      end: 76000000
      color: '#DAD9DE'
      resolution: 5000

  - name: Blank
    type: bw
    gs:
      row:
        from: 2
        to: 
      col: 
        from: 0
        to:

    pars:
      bwfile: /annoroad/data1/bioinfo/PMO/yuanzan/RD/WDL/bw_track5/script/blankA.bw
      chrom: chr13
      start: 72000000
      end: 76000000
      color: '#E0BCC8'
      resolution: 5000

  
  


