
figure:
  size: 
    width: 7
    height: 12

  row: 18
  col: 1

tracks:
  - name: 2-cell
    type: triView
    gs:
      row:
        from: 2
        to: 4
      col: 
        from: 0
        to:

    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/h2cell_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000

  - name: 8-cell
    type: triView
    gs:
      row:
        from: 4
        to: 6
      col: 
        from: 0
        to:
    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/h8cell_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000

  - name: Morula
    type: triView
    gs:
      row:
        from: 6
        to: 8
      col: 
        from: 0
        to:
    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/morula_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000

  - name: Blastocyst
    type: triView
    gs:
      row:
        from: 8
        to: 10
      col: 
        from: 0
        to:
    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/blastocyst_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000

  - name: 6-week
    type: triView
    gs:
      row:
        from: 10
        to: 12
      col: 
        from: 0
        to:
    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/h6week_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000

  - name: H1 hESC
    type: triView
    gs:
      row:
        from: 12
        to: 14
      col: 
        from: 0
        to:
    pars:
      abs.bed: ../../test_data/hg19_chr7_40000_abs.bed
      matrix: ../../test_data/H1ESC_chr7_400_730_40k_raw.mat
      resolution: 40000
      show_distance: 2000000
      chrom: chr7
      start: 17000000
      end: 28940000



  
  


