sphinx:
  recursive_update: true
  extra_extensions:
  - sphinx_inline_tabs
  
  config:
    project: TrackC
    master_doc: index
    html_theme: pydata_sphinx_theme
    autosummary_generate: True
    html_show_sphinx: False
    pygments_style: sphinx
    highlight_language: python3
