sphinx:
  recursive_update: true
  extra_extensions:
  - sphinx_inline_tabs
  - sphinx_gallery.load_style
  - sphinx.ext.graphviz
  - nbsphinx
  - IPython.sphinxext.ipython_console_highlighting
  - sphinxcontrib.bibtex
  - sphinx.ext.autosummary
  - sphinx_copybutton
  
  config:
    project: TrackC
    master_doc: index
    html_theme: pydata_sphinx_theme
    autosummary_generate: True
    html_show_sphinx: False
    pygments_style: sphinx
    highlight_language: python3
